version: '3.9'

services:
  web:
    build: .
    container_name: geomapgov_web
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    expose:
      - '8000'
    restart: always

  bot:
    build: .
    container_name: geomapgov_bot
    command: python bot/main.py
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    restart: always

  nginx:
    image: nginx:1.24
    container_name: geomapgov_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/geomapgov.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    restart: always
